using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using BepInEx;

namespace MyAwesomeWhitelist.I18n
{
    /// <summary>
    /// A loaded language: its code (from filename), display name (from __LANG_NAME__),
    /// and key→value map.
    /// </summary>
    internal sealed class Language
    {
        public string Code;          // e.g. "zh-cn", "en", "jp"
        public string DisplayName;   // e.g. "简体中文", "English", "日本語"
        public readonly Dictionary<string, string> Map = new Dictionary<string, string>();
    }

    /// <summary>
    /// Localization manager. Scans the lang/ directory for *.txt files, builds per-language
    /// maps, and resolves keys with fallback: current → English → key itself.
    /// Switching languages takes effect immediately.
    ///
    /// Language file format (one per line):
    ///   <code>KEY:Translation</code>
    ///   Lines starting with '#' are comments. Blank lines ignored.
    ///   Special key <c>__LANG_NAME__</c> sets the display name for the picker.
    ///   Escape '\n' in values becomes newline.
    /// </summary>
    internal sealed class LocalizationService
    {
        private static LocalizationService _instance;
        private readonly Dictionary<string, Language> _languages = new Dictionary<string, Language>();
        private Language _current;
        private Language _english;

        public static LocalizationService Instance { get { return _instance; } }

        /// <summary>All loaded languages, English first then others.</summary>
        public IEnumerable<Language> Languages
        {
            get
            {
                if (_english != null) yield return _english;
                foreach (var kvp in _languages)
                    if (kvp.Value != _english) yield return kvp.Value;
            }
        }

        /// <summary>Current language code (e.g. "zh-cn").</summary>
        public string CurrentCode => _current != null ? _current.Code : "en";

        public static void Init()
        {
            _instance = new LocalizationService();
            _instance.Reload();
        }

        /// <summary>(Re)scan lang/ directory and build all maps.</summary>
        public void Reload()
        {
            _languages.Clear();
            _english = null;
            _current = null;

            // Always generate default files on first run (idempotent — won't overwrite user edits).
            EnsureDefaultFiles();

            string langDir = LangDir;
            if (!Directory.Exists(langDir))
                return;

            foreach (var path in Directory.GetFiles(langDir, "*.txt"))
            {
                string code = Path.GetFileNameWithoutExtension(path);
                string displayName;
                var entries = LangFile.Parse(path, out displayName);

                var lang = new Language { Code = code };
                foreach (var e in entries)
                    lang.Map[e.Key] = e.Value;
                lang.DisplayName = displayName ?? code;

                // Top up keys this plugin version knows about but the file
                // (generated by an older version) is missing — both in memory
                // and on disk, so the value never falls back to the raw key.
                TopUpMissingKeys(path, code, lang);

                _languages[code] = lang;
                if (code == "en") _english = lang;
            }

            // If no en.txt exists yet, generate it from zh-cn as base.
            if (_english == null && _languages.ContainsKey("zh-cn"))
            {
                GenerateEnglishFrom(_languages["zh-cn"]);
            }

            // Auto-detect on first launch: use saved preference > system locale > "en".
            string preferred = Plugin.Config.LanguageCode.Value;
            string detected = DetectSystemLocale();
            string target = _languages.ContainsKey(preferred) ? preferred
                         : (_languages.ContainsKey(detected) ? detected : "en");
            SetLanguage(target);

            Plugin.Logger.LogInfo($"[I18n] Loaded {_languages.Count} language(s): {string.Join(", ", _languages.Keys)} · active: {CurrentCode}");
        }

        /// <summary>Set current language by code. Returns false if not found.</summary>
        public bool SetLanguage(string code)
        {
            if (code == null || !_languages.ContainsKey(code))
                return false;
            _current = _languages[code];
            return true;
        }

        /// <summary>Resolve a key: current → English → key itself.</summary>
        public string Get(string key)
        {
            if (string.IsNullOrEmpty(key)) return string.Empty;

            // 1) Current language
            if (_current != null)
            {
                string v;
                if (_current.Map.TryGetValue(key, out v) && !string.IsNullOrEmpty(v))
                    return v;
            }
            // 2) English fallback
            if (_english != null && _current != _english)
            {
                string v;
                if (_english.Map.TryGetValue(key, out v) && !string.IsNullOrEmpty(v))
                    return v;
            }
            // 3) Key itself as last resort
            return key;
        }

        /// <summary>Display name for a language picker.</summary>
        public string DisplayNameOf(string code)
        {
            Language lang;
            return _languages.TryGetValue(code, out lang) ? (lang.DisplayName ?? code) : code;
        }

        /// <summary>Available language codes for a dropdown/picker.</summary>
        public string[] AvailableCodes
        {
            get
            {
                var list = new List<string>(_languages.Keys);
                list.Sort();
                return list.ToArray();
            }
        }

        // ── File management ───────────────────────────────────────────

        private static string LangDir => Path.Combine(Paths.ConfigPath, PluginInfo.PLUGIN_NAME, "lang");

        /// <summary>Built-in defaults per language code ("key:value" lines).</summary>
        private static Dictionary<string, string[]> DefaultLines()
        {
            // Reflection-free: the writer methods below own the line arrays,
            // but they are also needed here for top-up, so duplicate the call.
            return new Dictionary<string, string[]>
            {
                { "zh-cn", ZhCnLines() },
                { "en", EnLines() },
                { "jp", JpLines() },
            };
        }

        /// <summary>Append any keys present in the built-in defaults but
        /// missing from the user's (possibly older) file, then add them to
        /// the in-memory map. Never touches keys the user already has.</summary>
        private static void TopUpMissingKeys(string path, string code, Language lang)
        {
            Dictionary<string, string[]> defaults;
            try { defaults = DefaultLines(); }
            catch { return; }
            string[] lines;
            if (!defaults.TryGetValue(code, out lines)) return;

            var missing = new List<string>();
            for (int i = 0; i < lines.Length; i++)
            {
                string line = lines[i];
                int colon = line.IndexOf(':');
                if (colon <= 0) continue; // comment / blank
                string key = line.Substring(0, colon);
                if (key == "__LANG_NAME__" || lang.Map.ContainsKey(key)) continue;
                lang.Map[key] = line.Substring(colon + 1);
                missing.Add(line);
            }
            if (missing.Count == 0) return;
            try
            {
                File.AppendAllText(path,
                    Environment.NewLine + "# --- added by upgrade (v" + PluginInfo.PLUGIN_VERSION + ") ---" + Environment.NewLine
                    + string.Join(Environment.NewLine, missing.ToArray()) + Environment.NewLine,
                    new UTF8Encoding(false));
                Plugin.Logger.LogInfo($"[I18n] Added {missing.Count} new key(s) to {Path.GetFileName(path)}");
            }
            catch (Exception e)
            {
                Plugin.Logger.LogWarning($"[I18n] Could not append new keys to {Path.GetFileName(path)}: {e.Message}");
            }
        }

        private void EnsureDefaultFiles()
        {
            Directory.CreateDirectory(LangDir);

            // Only create defaults if the directory is empty or missing target files.
            if (!File.Exists(Path.Combine(LangDir, "zh-cn.txt")))
                WriteDefaultZhCn();
            if (!File.Exists(Path.Combine(LangDir, "en.txt")))
                WriteDefaultEn();
            if (!File.Exists(Path.Combine(LangDir, "jp.txt")))
                WriteDefaultJp();
        }

        private static void WriteDefaultZhCn()
        {
            File.WriteAllLines(Path.Combine(LangDir, "zh-cn.txt"), ZhCnLines(), new UTF8Encoding(false));
        }

        private static string[] ZhCnLines()
        {
            return new[]
            {
                "# MyAwesomeWhitelist 简体中文翻译",
                "__LANG_NAME__:简体中文",
                "",
                "# === 窗口标题 / Tab 名称 ===",
                "TAB_PLAYERS:玩家列表",
                "TAB_WHITELIST:白名单",
                "TAB_BLACKLIST:黑名单",
                "TAB_FRIENDS:好友",
                "TAB_SETTINGS:设置",
                "",
                "# === 状态行 ===",
                "HOST_IS:本机是否为主机:是",
                "HOST_NOT:本机是否为主机:否 — 各项操作仅主机生效",
                "HOST_MODE:本机是否为主机:是",
                "NOT_HOST:本机是否为主机:否 — 各项操作仅主机生效",
                "WHITELIST_TOGGLE:白名单",
                "BLACKLIST_TOGGLE:黑名单",
                "",
                "# === 玩家列表 ===",
                "ONLINE_PLAYERS:在线玩家({0})",
                "NO_PLAYERS:暂无其他玩家",
                "WAITING_LOBBY:等待主机会话…",
                "ENFORCE_WHITELIST:执行白名单踢出(踢出当前房间内所有不在白名单中的玩家)",
                "ENFORCE_BLACKLIST:执行黑名单踢出(踢出当前房间内所有在黑名单中的玩家)",
                "ENFORCE_BLACKLIST_NONE:当前房间内没有在黑名单中的玩家",
                "AUTO_BLACKLIST_NOTE:黑名单为自动踢出:名单内玩家每秒检查并强制踢出,无需手动操作",
                "",
                "# === 按钮操作 ===",
                "BTN_KICK:踢出",
                "BTN_KICK_TEMPBLACK:踢+临黑",
                "BTN_KICK_PERMBLACK:踢+永黑",
                "BTN_WHITE_TEMP:加白·临",
                "BTN_WHITE_PERM:加白·永",
                "BTN_BLACK_TEMP:拉黑·临",
                "BTN_BLACK_PERM:拉黑·永",
                "BTN_DELETE:删除",
                "BTN_UNWHITE:移出白",
                "BTN_UNBLACK:移出黑",
                "BTN_CLOSE:✕",
                "",
                "# === 名单列表 ===",
                "LIST_PERM:永久",
                "LIST_TEMP:临时",
                "LIST_EMPTY:(空)",
                "SETTINGS_LANG:语言 / Language",
                "FILTER_ALL:全部",
                "FILTER_PERM:永久",
                "FILTER_TEMP:临时",
                "LIST_COUNT:{0}名单:永久 {1} · 临时 {2}",
                "MANUAL_ADD:手动添加(SteamID64)",
                "MANUAL_ADD_PERM:永久",
                "MANUAL_ADD_TEMP:临时",
                "INVALID_STEAMID:无效的 SteamID64",
                "ALREADY_IN_LIST:该玩家已在名单中",
                "UNKNOWN_PLAYER:(未知)",
                "PENDING_IDENTIFY:(待识别)",
                "",
                "# === 好友 tab ===",
                "FRIENDS_TITLE:Steam 好友列表",
                "FRIENDS_DESC:从你的 Steam 好友中一键添加到白名单或黑名单。",
                "FRIENDS_SEARCH:搜索(前缀):",
                "NO_FRIENDS:未获取到好友列表(Steam 未连接?)",
                "",
                "# === 设置 tab ===",
                "SETTINGS_HOTKEY:开窗热键",
                "SETTINGS_HOTKEY_DESC:组合键格式:修饰键 + 主键,如 Ctrl+Shift+W、Alt+F6。Ctrl 在 macOS 上匹配 Cmd。保存后立即生效。",
                "SETTINGS_SAVE:保存",
                "SETTINGS_INVALID_KEY:无效的热键(修饰键 Ctrl/Shift/Alt + 主键,主键如 W、F6、Home)",
                "SETTINGS_SAVED:热键已保存: {0}",
                "",
                "SETTINGS_ABOUT:关于",
                "SETTINGS_ABOUT_DESC:强制踢出在主机端执行(销毁对象 + Steam P2P 拒绝重连),客户端防踢补丁无法拦截。",
                "SETTINGS_FILES:名单文件:",
                "",
                "# === Toast 提示 ===",
                "TOAST_KICKED:已踢出 {0}",
                "TOAST_ADDED:已添加到{0}名单:{1}",
                "TOAST_DELETED:已删除 {0}",
                "TOAST_BLACKLISTED:已拉黑({0}):{1}",
                "TOAST_KICKED_BLACKLISTED:已踢出并{0}拉黑:{1}",
                "TOAST_ENFORCED:已踢出黑名单玩家:{0}",
                "TOAST_ENFORCED_N:已执行白名单踢出:{0} 人被踢出",
                "TOAST_NO_ENFORCED:当前房间内没有在黑名单中的玩家",
                "TOAST_NO_ENFORCED_W:当前房间内没有不在白名单中的玩家",
                "",
                "# === 名称解析 ===",
                "NAME_CACHE_FAIL:Steam 名称查询失败",
            };
        }

        private static void WriteDefaultEn()
        {
            File.WriteAllLines(Path.Combine(LangDir, "en.txt"), EnLines(), new UTF8Encoding(false));
        }

        private static string[] EnLines()
        {
            return new[]
            {
                "# MyAwesomeWhitelist English translations",
                "__LANG_NAME__:English",
                "",
                "TAB_PLAYERS:Players",
                "TAB_WHITELIST:Whitelist",
                "TAB_BLACKLIST:Blacklist",
                "TAB_FRIENDS:Friends",
                "TAB_SETTINGS:Settings",
                "",
                "HOST_IS:Is this machine the host: Yes",
                "HOST_NOT:Is this machine the host: No — actions only work for the host",
                "HOST_MODE:Is this machine the host: Yes",
                "NOT_HOST:Is this machine the host: No — actions only work for the host",
                "WHITELIST_TOGGLE:Whitelist",
                "BLACKLIST_TOGGLE:Blacklist",
                "",
                "ONLINE_PLAYERS:Online players ({0})",
                "NO_PLAYERS:No other players",
                "WAITING_LOBBY:Waiting for lobby…",
                "ENFORCE_WHITELIST:Enforce whitelist (kick everyone currently in the lobby who is not whitelisted)",
                "ENFORCE_BLACKLIST:Enforce blacklist (kick all blacklisted players currently in lobby)",
                "ENFORCE_BLACKLIST_NONE:No blacklisted players in current lobby",
                "AUTO_BLACKLIST_NOTE:Blacklist is enforced automatically: blacklisted players are checked and force-kicked every second, no button needed",
                "",
                "BTN_KICK:Kick",
                "BTN_KICK_TEMPBLACK:Kick+TempBl",
                "BTN_KICK_PERMBLACK:Kick+PermBl",
                "BTN_WHITE_TEMP:Wht·Temp",
                "BTN_WHITE_PERM:Wht·Perm",
                "BTN_BLACK_TEMP:Blk·Temp",
                "BTN_BLACK_PERM:Blk·Perm",
                "BTN_DELETE:Del",
                "BTN_UNWHITE:Unwhite",
                "BTN_UNBLACK:Unblack",
                "BTN_CLOSE:✕",
                "",
                "LIST_PERM:Perm",
                "LIST_TEMP:Temp",
                "LIST_EMPTY:(empty)",
                "SETTINGS_LANG:Language / 语言",
                "FILTER_ALL:All",
                "FILTER_PERM:Permanent",
                "FILTER_TEMP:Temporary",
                "LIST_COUNT:{0}: Perm {1} · Temp {2}",
                "MANUAL_ADD:Add player (SteamID64)",
                "MANUAL_ADD_PERM:Permanent",
                "MANUAL_ADD_TEMP:Temporary",
                "INVALID_STEAMID:Invalid SteamID64",
                "ALREADY_IN_LIST:Player already in list",
                "UNKNOWN_PLAYER:(unknown)",
                "PENDING_IDENTIFY:(pending)",
                "",
                "FRIENDS_TITLE:Steam Friends",
                "FRIENDS_DESC:One-click add friends to whitelist or blacklist.",
                "FRIENDS_SEARCH:Search (prefix):",
                "NO_FRIENDS:No friends found (Steam offline?)",
                "",
                "SETTINGS_HOTKEY:Toggle hotkey",
                "SETTINGS_HOTKEY_DESC:Format: Modifiers + Key, e.g. Ctrl+Shift+W. Ctrl matches Cmd on macOS.",
                "SETTINGS_SAVE:Save",
                "SETTINGS_INVALID_KEY:Invalid hotkey spec",
                "SETTINGS_SAVED:Hotkey saved: {0}",
                "",
                "SETTINGS_ABOUT:About",
                "SETTINGS_ABOUT_DESC:Force-kick runs server-side teardown + P2P reconnect refusal — client anti-kick mods cannot block it.",
                "SETTINGS_FILES:List files:",
                "",
                "TOAST_KICKED:Kicked {0}",
                "TOAST_ADDED:Added to {0} list: {1}",
                "TOAST_DELETED:Deleted {0}",
                "TOAST_BLACKLISTED:Blacklisted ({0}): {1}",
                "TOAST_KICKED_BLACKLISTED:Kicked + {0}blacklisted: {1}",
                "TOAST_ENFORCED:Kicked blacklisted player: {0}",
                "TOAST_ENFORCED_N:Whitelist enforced: {0} player(s) kicked",
                "TOAST_NO_ENFORCED:No blacklisted players in lobby",
                "TOAST_NO_ENFORCED_W:Everyone in the lobby is already whitelisted",
                "",
                "NAME_CACHE_FAIL:Steam name lookup failed",
            };
        }

        private static void WriteDefaultJp()
        {
            File.WriteAllLines(Path.Combine(LangDir, "jp.txt"), JpLines(), new UTF8Encoding(false));
        }

        private static string[] JpLines()
        {
            return new[]
            {
                "# MyAwesomeWhitelist 日本語翻訳",
                "__LANG_NAME__:日本語",
                "",
                "TAB_PLAYERS:プレイヤーリスト",
                "TAB_WHITELIST:ホワイトリスト",
                "TAB_BLACKLIST:ブラックリスト",
                "TAB_FRIENDS:フレンド",
                "TAB_SETTINGS:設定",
                "",
                "HOST_IS:このPCがホストか: はい",
                "HOST_NOT:このPCがホストか: いいえ — 操作はホストのみ有効",
                "HOST_MODE:このPCがホストか: はい",
                "NOT_HOST:このPCがホストか: いいえ — 操作はホストのみ有効",
                "WHITELIST_TOGGLE:ホワイトリスト",
                "BLACKLIST_TOGGLE:ブラックリスト",
                "",
                "ONLINE_PLAYERS:オンラインプレイヤー({0})",
                "NO_PLAYERS:他のプレイヤーはいません",
                "WAITING_LOBBY:ロビーを待っています…",
                "ENFORCE_WHITELIST:ホワイトリスト実行(ロビー内のホワイトリスト未登録者をキック)",
                "ENFORCE_BLACKLIST:ブラックリスト実行(現在のロビーにいるブラックリスト登録者をキック)",
                "ENFORCE_BLACKLIST_NONE:現在のロビーにブラックリスト登録者はいません",
                "AUTO_BLACKLIST_NOTE:ブラックリストは自動キック:登録者は毎秒チェックされ強制キックされます(ボタン不要)",
                "",
                "BTN_KICK:キック",
                "BTN_KICK_TEMPBLACK:キック+一時B",
                "BTN_KICK_PERMBLACK:キック+恒久B",
                "BTN_WHITE_TEMP:白・一時",
                "BTN_WHITE_PERM:白・恒久",
                "BTN_BLACK_TEMP:黒・一時",
                "BTN_BLACK_PERM:黒・恒久",
                "BTN_DELETE:削除",
                "BTN_UNWHITE:白解除",
                "BTN_UNBLACK:黒解除",
                "BTN_CLOSE:✕",
                "",
                "LIST_PERM:恒久",
                "LIST_TEMP:一時",
                "LIST_EMPTY:(空)",
                "SETTINGS_LANG:言語 / Language",
                "FILTER_ALL:全て",
                "FILTER_PERM:恒久",
                "FILTER_TEMP:一時",
                "LIST_COUNT:{0}リスト:恒久 {1} · 一時 {2}",
                "MANUAL_ADD:手動追加(SteamID64)",
                "MANUAL_ADD_PERM:恒久",
                "MANUAL_ADD_TEMP:一時",
                "INVALID_STEAMID:無効な SteamID64",
                "ALREADY_IN_LIST:既にリストに存在します",
                "UNKNOWN_PLAYER:(不明)",
                "PENDING_IDENTIFY:(識別待ち)",
                "",
                "FRIENDS_TITLE:Steam フレンドリスト",
                "FRIENDS_DESC:Steam フレンドからホワイトリスト/ブラックリストに一括追加。",
                "FRIENDS_SEARCH:検索(前方一致):",
                "NO_FRIENDS:フレンドリスト取得失敗(Steam オフライン?)",
                "",
                "SETTINGS_HOTKEY:ウィンドウ表示キー",
                "SETTINGS_HOTKEY_DESC:書式: 修飾キー + メインキー。例: Ctrl+Shift+W。macOS では Ctrl が Cmd に対応。",
                "SETTINGS_SAVE:保存",
                "SETTINGS_INVALID_KEY:無効なキー指定",
                "SETTINGS_SAVED:キーを保存: {0}",
                "",
                "SETTINGS_ABOUT:情報",
                "SETTINGS_ABOUT_DESC:強制キックはサーバー側で実行(オブジェクト破棃 + P2P 再接続拒否)。クライアント側の対策MODは阻止できません。",
                "SETTINGS_FILES:リストファイル:",
                "",
                "TOAST_KICKED:{0} をキックしました",
                "TOAST_ADDED:{0}リストに追加: {1}",
                "TOAST_DELETED:{0} を削除",
                "TOAST_BLACKLISTED:ブラックリスト追加({0}): {1}",
                "TOAST_KICKED_BLACKLISTED:キック + {0}ブラックリスト: {1}",
                "TOAST_ENFORCED:ブラックリストプレイヤーをキック: {0}",
                "TOAST_ENFORCED_N:ホワイトリスト実行: {0} 人をキックしました",
                "TOAST_NO_ENFORCED:ブラックリスト登録者はいません",
                "TOAST_NO_ENFORCED_W:ロビー内の全員がホワイトリスト登録済みです",
                "",
                "NAME_CACHE_FAIL:Steam名前取得失敗",
            };
        }

        private void GenerateEnglishFrom(Language source)
        {
            var en = new Language { Code = "en", DisplayName = "English" };
            // For each source entry, keep the key but use the key itself as value
            // (so at least the UI shows something readable).
            foreach (var kv in source.Map)
                en.Map[kv.Key] = kv.Key; // key-as-value fallback
            _languages["en"] = en;
            _english = en;

            // Write it to disk so user can edit later.
            var lines = new List<string> { "# Auto-generated English fallback (edit freely)", $"__LANG_NAME__:English", "" };
            foreach (var kv in en.Map)
                lines.Add($"{kv.Key}:{kv.Value}");
            // Sort keys for deterministic output.
            lines.Sort();
            File.WriteAllLines(Path.Combine(LangDir, "en.txt"), lines, new UTF8Encoding(false));
        }

        private string DetectSystemLocale()
        {
            // Try to match system language to our available codes.
            try
            {
                string sysLang = UnityEngine.Application.systemLanguage.ToString();
                if (sysLang != null)
                {
                    string sl = sysLang.ToLowerInvariant();
                    if (sl.Contains("chinese") || sl.Contains("zh")) return "zh-cn";
                    if (sl.Contains("japanese") || sl.Contains("jp")) return "jp";
                    if (sl.Contains("english") || sl.Contains("en")) return "en";
                }
            }
            catch { /* ignore */ }
            return "en";
        }
    }
}
